# https://gcr.io/tensorflow/tensorflow
# https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker
device: cpu
tensorflow-base-image: gcr.io/tensorflow/tensorflow:1.2.1

# https://golang.org/dl/
go-version: 1.9rc2

# https://github.com/creationix/nvm/releases
nvm-version: 0.33.2

# https://github.com/nodejs/LTS#lts-schedule1
node-version: 8.4.0

dockerfile-paths:
- ./dockerfiles/cpu/Dockerfile
