# https://gcr.io/tensorflow/tensorflow
# https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker
device: gpu
tensorflow-base-image: gcr.io/tensorflow/tensorflow:1.2.0-rc2-gpu

# https://golang.org/dl/
go-version: 1.9beta1

# https://github.com/creationix/nvm/releases
nvm-version: 0.33.2

# https://github.com/nodejs/LTS#lts-schedule1
# 8.0.0
node-version: 7.10.0

dockerfile-paths:
- ./dockerfiles/gpu/Dockerfile
